import {test, expect} from '@playwright/test'

test('pausing a local table freezes both visible clocks and resumes the remaining turn', async ({page}) => {
  await page.clock.install({time: new Date('2026-09-25T12:00:00Z')})
  await page.clock.pauseAt(new Date('2026-09-25T12:00:01Z'))
  await page.goto('local')
  await expect(page.getByRole('heading', {name: 'Runde vorbereiten'})).toBeVisible()
  await expect(page.getByRole('button', {name: 'Alles klar'})).toHaveCount(0)
  await page.getByRole('button', {name: 'Lokalen Tisch starten'}).click()
  await page.getByRole('button', {name: 'Hand starten & Blinds buchen'}).click()
  const turn = page.locator('.local-controls h2')
  const blinds = page.locator('.local-status')
  await expect(turn).toContainText('00:30')
  await expect(blinds).toContainText('Level in 20:00')
  await page.getByRole('button', {name: '⏸ Pausieren'}).click()
  const pausedTurn = await turn.textContent()
  const pausedBlinds = await blinds.textContent()
  await page.clock.fastForward(61_000)
  await expect(turn).toHaveText(pausedTurn!)
  await expect(blinds).toHaveText(pausedBlinds!)
  await page.getByRole('button', {name: 'Fortsetzen', exact: true}).click()
  await expect(turn).toHaveText(pausedTurn!)
  await expect(blinds).toHaveText(pausedBlinds!)
  await page.clock.fastForward(10_000)
  await expect(turn).toContainText('00:20')
  await expect(blinds).toContainText('Level in 19:50')
})
